# ----------------------------
# Makefile Options
# ----------------------------

NAME = COMICS
DESCRIPTION = "eBookSync comic reader"
COMPRESSED = YES
ARCHIVED = YES

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
