/* Generated by tools/stage_update.sh. Do not edit. */

/*
 * The build this page came from, shown in the header.
 *
 * It is the same number the calculator reports over HELLO, so a page and a
 * reader can be told apart from each other at a glance.
 */
export const PAGE_BUILD = 19;
