#!/usr/bin/env python3
"""Check the reader's font: complete, well-formed, and what the generator makes.

calc/src/fontdata.c is generated by tools/make_font.py and committed, so the
calculator build does not need Pillow or the fonts. That makes two ways for it
to go wrong quietly -- edited by hand, or left behind when the generator
changed -- and one more on the calculator: an offset or width that walks off
the end of the glyph bits draws whatever follows them in memory.

    tools/hosttest/check_font.py
"""

import re
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
FONTDATA = ROOT / "calc" / "src" / "fontdata.c"
FONTS = Path("/usr/share/fonts/truetype/dejavu")

failures = []
checks = 0


def check(label, ok, detail=""):
    global checks
    checks += 1
    if not ok:
        failures.append(f"{label}{': ' + detail if detail else ''}")


def faces(source):
    """{name: (height, ascent, glyphs [(offset, width, advance, shift)], bit count)}."""
    out = {}
    for name, height, ascent in re.findall(
            r"const ui_font_t (\w+) = \{ (\d+), (\d+), \w+, \w+ \};", source):
        glyphs = [tuple(map(int, g)) for g in re.findall(
            r"\{ (\d+), (\d+), (\d+), (\d+) \},", source.split(f"{name}_glyphs[] = {{")[1]
            .split("};")[0])]
        bits = source.split(f"{name}_bits[] = {{")[1].split("};")[0]
        out[name] = (int(height), int(ascent), glyphs, len(re.findall(r"0x[0-9A-F]{2}", bits)))
    return out


def main():
    source = FONTDATA.read_text()
    found = faces(source)
    check("three faces", sorted(found) == ["font_body", "font_bold", "font_small"], str(sorted(found)))

    for name, (height, ascent, glyphs, bits) in found.items():
        check(f"{name}: every printable ASCII character", len(glyphs) == 95, str(len(glyphs)))
        check(f"{name}: the baseline is inside the cell", 0 < ascent <= height)
        for code, (offset, width, advance, shift) in zip(range(32, 127), glyphs):
            stride = (width + 3) // 4
            ok = width > 0 and advance > 0 and offset + stride * height <= bits
            check(f"{name} {chr(code)!r}: inside the glyph bits", ok,
                  f"offset {offset}, width {width}, {bits} bytes")
            check(f"{name} {chr(code)!r}: the cell holds the advance", width >= advance)
        # The row height the menus are laid out around.
        check(f"{name}: fits a list row", height <= 20, str(height))

    check("the licence notice is there", "Bitstream Vera" in source)

    if FONTS.exists():
        with tempfile.TemporaryDirectory() as tmp:
            out = Path(tmp) / "fontdata.c"
            subprocess.run([sys.executable, str(ROOT / "tools" / "make_font.py"),
                            "--fonts", str(FONTS), "--out", str(out)],
                           check=True, capture_output=True)
            check("fontdata.c is what make_font.py makes now", out.read_text() == source,
                  "regenerate it with tools/make_font.py")
    else:
        print(f"  ({FONTS} not here; not regenerating to compare)")

    for failure in failures:
        print(f"  FAIL {failure}")
    print(f"{checks - len(failures)}/{checks} font checks pass")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
