#!/usr/bin/env python3
"""Render the reader's font into calc/src/fontdata.c.

graphx's built-in font is 8x8, fixed width and one weight, and in 20-pixel rows
it read as cramped. This renders DejaVu Sans -- a proportional face with proper
spacing -- at a few sizes, anti-aliased to four levels, into the same 2bpp form
the page already uses for titles. calc/src/font.c draws it through a palette
ramp, exactly as a title is drawn, so text sits correctly on any background in
either theme.

The output is committed. Regenerating it needs Pillow and the DejaVu fonts,
which the calculator build does not, so `make` does not run this:

    tools/make_font.py [--fonts /usr/share/fonts/truetype/dejavu]

DejaVu Sans is under the Bitstream Vera licence (with the DejaVu changes in the
public domain), which permits exactly this: using the glyphs, rendered, inside
a program. The notice goes into the generated file.
"""

import argparse
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parent.parent
FIRST, LAST = 32, 126

# (C name, file, pixel size). Body for lists and prose, bold for headers and
# emphasis, small for key hints and the diagnostic strip.
FACES = [
    ("font_body", "DejaVuSans.ttf", 12),
    ("font_bold", "DejaVuSans-Bold.ttf", 13),
    ("font_small", "DejaVuSans.ttf", 10),
]

NOTICE = """/*
 * Generated by tools/make_font.py. Do not edit; regenerate it instead.
 *
 * Glyphs rendered from DejaVu Sans. Bitstream Vera Fonts Copyright (c) 2003 by
 * Bitstream, Inc. All Rights Reserved. Bitstream Vera is a trademark of
 * Bitstream, Inc. DejaVu changes are in the public domain. Permission is
 * granted to use the fonts under the terms of the Bitstream Vera licence; see
 * https://dejavu-fonts.github.io/License.html
 */
"""


def level(value):
    """Coverage 0-255 to 0-3, biased up a little: thin strokes at this size are
    mostly partial coverage, and rounding them down loses them."""
    return min(3, (value * 3 + 96) // 255)


def render_face(path, size):
    font = ImageFont.truetype(str(path), size)
    ascent, descent = font.getmetrics()
    height = ascent + descent

    glyphs = []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        advance = max(1, round(font.getlength(ch)))
        left, _, right, _ = font.getbbox(ch)
        # The cell covers the ink as well as the advance, so a glyph whose ink
        # overhangs its advance (italic-ish tails, 'j') is not clipped; drawing
        # moves on by the advance, not the cell.
        shift = -min(0, left)
        width = max(advance + shift, right + shift, 1)

        image = Image.new("L", (width, height), 0)
        ImageDraw.Draw(image).text((shift, 0), ch, font=font, fill=255)
        pixels = image.load()

        stride = (width + 3) // 4
        packed = bytearray(stride * height)
        for y in range(height):
            for x in range(width):
                lv = level(pixels[x, y])
                if lv:
                    packed[y * stride + x // 4] |= lv << (6 - 2 * (x % 4))
        glyphs.append({"advance": advance, "width": width, "shift": shift, "bits": packed})
    return height, ascent, glyphs


def c_bytes(data, indent="    "):
    lines = []
    for i in range(0, len(data), 16):
        lines.append(indent + ", ".join(f"0x{b:02X}" for b in data[i:i + 16]) + ",")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--fonts", default="/usr/share/fonts/truetype/dejavu")
    parser.add_argument("--out", default=str(ROOT / "calc" / "src" / "fontdata.c"))
    args = parser.parse_args()

    out = [NOTICE, '#include "font.h"', ""]
    total = 0
    for name, filename, size in FACES:
        path = Path(args.fonts) / filename
        if not path.exists():
            sys.exit(f"{path} not found; pass --fonts")
        height, ascent, glyphs = render_face(path, size)

        bits = bytearray()
        offsets = []
        for glyph in glyphs:
            offsets.append(len(bits))
            bits += glyph["bits"]
        total += len(bits)

        out.append(f"/* {filename} at {size}px: {height} rows, {len(bits)} bytes of glyphs. */")
        out.append(f"static const uint8_t {name}_bits[] = {{")
        out.append(c_bytes(bits))
        out.append("};")
        out.append(f"static const ui_glyph_t {name}_glyphs[] = {{")
        for code, glyph, offset in zip(range(FIRST, LAST + 1), glyphs, offsets):
            shown = chr(code) if chr(code) not in "\\'" else "\\" + chr(code)
            out.append(f"    {{ {offset}, {glyph['width']}, {glyph['advance']}, "
                       f"{glyph['shift']} }},   /* '{shown}' */")
        out.append("};")
        out.append(f"const ui_font_t {name} = {{ {height}, {ascent}, {name}_glyphs, {name}_bits }};")
        out.append("")

    Path(args.out).write_text("\n".join(out))
    print(f"wrote {args.out}: {len(FACES)} faces, {total} bytes of glyphs")


if __name__ == "__main__":
    main()
